### ISSUE TITLE
Loadingscreen not Loading - Blackscreen

### ISSUE THREAD

**Issue by yiruzu** [Gustiagung19/gusti-loadscreen#1]
![image](https://user-images.githubusercontent.com/94981325/236576687-3094becb-dec8-4316-aa0f-65e1f2763c4e.png)

**Comment by Gustiagung19** [comment]
Most likely you haven't done a production build yet, please consult the documentation

### Documentation
- [AKL DOCUMENTATION](https://aklgaming.gitbook.io/documentation/gusti-resources/gusti-loadscreen)
